name: lingjin-dev
channels:
- defaults
dependencies:
- python=3.9
- pip=22.1.2
- pip:
    - pandas==2.2.0
    - numpy==1.26.3
    - plotly==5.14.1
    - scipy==1.11.4
    - adata==1.2.0
    - scikit-learn==1.3.0
    - statsmodels==0.14.1
    - sspipe==0.1.17
    - matplotlib==3.8.0